### ISSUE TITLE
Restore Backup

### ISSUE THREAD

**Issue by Gouds** [mycontroller-org/mycontroller#271] opened 2016-09-02 08:48 UTC
When Restoring a backup the Sensor Type reverted to Binary. (Was Sprinkler) Did not save the value. However Variable types was correct.

**Comment by jkandasa** [comment] 2016-09-02 09:10
@Gouds It might not be covered on your backup. Restore will change system state to backed up file state. Whatever you had when you trigger backup, your system will be moved to that state when you do restore.

**Comment by jkandasa** [comment] 2016-10-27 12:36
I am closing this issue, I am unable to reproduce this on locally. Feel free to reopen if you face this issue.

**Closed by jkandasa** 2016-10-27 12:36 UTC
