### ISSUE TITLE
Fresh install won't work with 0.0.3.Alpha2 (Migration Exception)

### ISSUE THREAD

**Issue by mozzbozz** [mycontroller-org/mycontroller#230] opened 2016-08-02 02:17 UTC
Afterwards I tried a 0.0.3.Alpha1 fresh install which works without any problems.

Anyway, here's the error log:

```
2016-08-02 03:53:28,708 ERROR [main] [org.mycontroller.standalone.db.DataBaseUtils:115] Migration exception, 
org.flywaydb.core.api.FlywayException: Found non-empty schema "PUBLIC" without metadata table! Use baseline() or set baselineOnMigrate to true to initialize the metadata table.
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1035) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1006) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
	at org.flywaydb.core.Flyway.execute(Flyway.java:1418) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1006) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
	at org.mycontroller.standalone.db.DataBaseUtils.loadDatabase(DataBaseUtils.java:113) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
	at org.mycontroller.standalone.StartApp.startServices(StartApp.java:243) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
	at org.mycontroller.standalone.StartApp.startMycontroller(StartApp.java:106) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
	at org.mycontroller.standalone.StartApp.main(StartApp.java:93) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
2016-08-02 03:53:34,746 INFO [main] [org.mycontroller.standalone.db.DataBaseUtils:154] Application information: [Version:0.0.3.Alpha2, Database version:null]
2016-08-02 03:53:34,905 ERROR [main] [org.mycontroller.standalone.settings.SettingsUtils:131] Unable to write static json information file! location:[../www/configurations/mycontroller-configs.json]
java.lang.NullPointerException: null
	at org.mycontroller.standalone.api.jaxrs.json.McGuiSettings.<init>(McGuiSettings.java:61) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
	at org.mycontroller.standalone.settings.SettingsUtils.updateStaticJsonInformationFile(SettingsUtils.java:128) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
	at org.mycontroller.standalone.StartApp.startServices(StartApp.java:246) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
	at org.mycontroller.standalone.StartApp.startMycontroller(StartApp.java:106) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
	at org.mycontroller.standalone.StartApp.main(StartApp.java:93) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
2016-08-02 03:53:34,910 ERROR [main] [org.mycontroller.standalone.StartApp:95] Unable to start application, refer error log,
java.lang.NullPointerException: null
	at org.mycontroller.standalone.utils.McUtils.updateLocale(McUtils.java:278) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
	at org.mycontroller.standalone.StartApp.startServices(StartApp.java:249) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
	at org.mycontroller.standalone.StartApp.startMycontroller(StartApp.java:106) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
	at org.mycontroller.standalone.StartApp.main(StartApp.java:93) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
Exception in thread "MyController.org Shutdown-Hook" java.lang.NullPointerException
	at Acme.Serve.Serve.stopBackground(Serve.java:684)
	at org.jboss.resteasy.plugins.server.tjws.TJWSServletServer.stop(TJWSServletServer.java:184)
	at org.mycontroller.standalone.StartApp.stopHTTPWebServer(StartApp.java:216)
	at org.mycontroller.standalone.StartApp.stopServices(StartApp.java:288)
	at org.mycontroller.standalone.AppShutdownHook$1.run(AppShutdownHook.java:34)
```

**Comment by jkandasa** [comment] 2016-08-02 10:10
@mozzbozz i don't see this issue.  can you post your os and java version details.  also post if have changed DB settings.  
Thank you

**Comment by mozzbozz** [comment] 2016-08-02 15:25
I haven't done any changes to the config files, it's the default one which ships within the zip archive.

My OS and kernel versions: 
```bash
pi@raspberrypi ~ $ uname -a
Linux raspberrypi 4.1.7+ #817 PREEMPT Sat Sep 19 15:25:36 BST 2015 armv6l GNU/Linux

pi@raspberrypi ~ $ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 8.0 (jessie)
Release:        8.0
Codename:       jessie
```

I could workaround this issue now: First I installed `0.0.3.Alpha1`, played around with it, backed it up, compeletely removed the installation directory and unziped `0.0.3.Alpha2` in exactly the same way. This time everything would work as expected. I guess the newer release tries to migrate some old database entries to a newer format even though they haven't been created yet. However, I'm wondering which database it uses, because I thought it's all stored within the installation directory... (then my guess would be wrong)

**Comment by mozzbozz** [comment] 2016-08-02 18:49
Well, after restoring my backup, I get a similar error message again...:

```bash
2016-08-02 20:46:25,732 ERROR [main] [org.mycontroller.standalone.db.DataBaseUtils:115] Migration exception,
org.flywaydb.core.api.FlywayException: Schema "PUBLIC" contains a failed migration to version 1.02.08 !
        at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:196) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:156) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:156) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1059) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1006) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.flywaydb.core.Flyway.execute(Flyway.java:1418) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.flywaydb.core.Flyway.migrate(Flyway.java:1006) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.mycontroller.standalone.db.DataBaseUtils.loadDatabase(DataBaseUtils.java:113) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.mycontroller.standalone.StartApp.startServices(StartApp.java:243) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.mycontroller.standalone.StartApp.startMycontroller(StartApp.java:106) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.mycontroller.standalone.StartApp.main(StartApp.java:93) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
2016-08-02 20:46:37,789 ERROR [main] [org.mycontroller.standalone.db.dao.BaseAbstractDaoImpl:254] unable to get all items
org.h2.jdbc.JdbcSQLException: Feld "lastSeen" nicht gefunden
Column "lastSeen" not found [42122-176]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:344) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.h2.message.DbException.get(DbException.java:178) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.h2.message.DbException.get(DbException.java:154) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3122) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.h2.jdbc.JdbcResultSet.findColumn(JdbcResultSet.java:182) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at com.j256.ormlite.jdbc.JdbcDatabaseResults.findColumn(JdbcDatabaseResults.java:90) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at com.j256.ormlite.field.FieldType.resultToJava(FieldType.java:815) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at com.j256.ormlite.stmt.mapped.BaseMappedQuery.mapRow(BaseMappedQuery.java:60) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at com.j256.ormlite.jdbc.JdbcDatabaseConnection.queryForOne(JdbcDatabaseConnection.java:283) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at com.j256.ormlite.jdbc.JdbcDatabaseConnection.queryForOne(JdbcDatabaseConnection.java:201) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at com.j256.ormlite.stmt.mapped.MappedQueryForId.execute(MappedQueryForId.java:38) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at com.j256.ormlite.field.FieldType.assignField(FieldType.java:558) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at com.j256.ormlite.stmt.mapped.BaseMappedQuery.mapRow(BaseMappedQuery.java:71) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at com.j256.ormlite.jdbc.JdbcDatabaseConnection.queryForOne(JdbcDatabaseConnection.java:283) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at com.j256.ormlite.jdbc.JdbcDatabaseConnection.queryForOne(JdbcDatabaseConnection.java:201) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at com.j256.ormlite.stmt.mapped.MappedQueryForId.execute(MappedQueryForId.java:38) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at com.j256.ormlite.field.FieldType.assignField(FieldType.java:558) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at com.j256.ormlite.stmt.mapped.BaseMappedQuery.mapRow(BaseMappedQuery.java:71) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at com.j256.ormlite.stmt.SelectIterator.getCurrent(SelectIterator.java:270) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at com.j256.ormlite.stmt.SelectIterator.nextThrow(SelectIterator.java:161) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at com.j256.ormlite.stmt.StatementExecutor.query(StatementExecutor.java:202) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at com.j256.ormlite.stmt.StatementExecutor.queryForAll(StatementExecutor.java:118) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at com.j256.ormlite.dao.BaseDaoImpl.queryForAll(BaseDaoImpl.java:241) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.mycontroller.standalone.db.dao.BaseAbstractDaoImpl.getAll(BaseAbstractDaoImpl.java:252) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.mycontroller.standalone.db.migration.V1_02_08__2016_Jul_01.migrate(V1_02_08__2016_Jul_01.java:74) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.flywaydb.core.internal.resolver.jdbc.JdbcMigrationExecutor.execute(JdbcMigrationExecutor.java:45) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.flywaydb.core.internal.command.DbMigrate$5.doInTransaction(DbMigrate.java:284) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.flywaydb.core.internal.command.DbMigrate$5.doInTransaction(DbMigrate.java:282) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.flywaydb.core.internal.command.DbMigrate.applyMigration(DbMigrate.java:282) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.flywaydb.core.internal.command.DbMigrate.access$800(DbMigrate.java:46) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:207) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:156) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:156) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1059) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1006) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.flywaydb.core.Flyway.execute(Flyway.java:1418) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.flywaydb.core.Flyway.migrate(Flyway.java:1006) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.mycontroller.standalone.db.DataBaseUtils.loadDatabase(DataBaseUtils.java:118) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.mycontroller.standalone.StartApp.startServices(StartApp.java:243) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.mycontroller.standalone.StartApp.startMycontroller(StartApp.java:106) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.mycontroller.standalone.StartApp.main(StartApp.java:93) [mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
2016-08-02 20:46:37,804 ERROR [main] [org.flywaydb.core.internal.command.DbMigrate:52] Migration of schema "PUBLIC" to version 1.02.08 failed! Please restore backups and roll back database and code!
2016-08-02 20:46:37,902 ERROR [main] [org.mycontroller.standalone.StartApp:95] Unable to start application, refer error log,
org.flywaydb.core.api.FlywayException: Migration failed !
        at org.flywaydb.core.internal.resolver.jdbc.JdbcMigrationExecutor.execute(JdbcMigrationExecutor.java:47) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.flywaydb.core.internal.command.DbMigrate$5.doInTransaction(DbMigrate.java:284) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.flywaydb.core.internal.command.DbMigrate$5.doInTransaction(DbMigrate.java:282) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.flywaydb.core.internal.command.DbMigrate.applyMigration(DbMigrate.java:282) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.flywaydb.core.internal.command.DbMigrate.access$800(DbMigrate.java:46) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:207) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:156) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:156) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1059) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1006) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.flywaydb.core.Flyway.execute(Flyway.java:1418) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.flywaydb.core.Flyway.migrate(Flyway.java:1006) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.mycontroller.standalone.db.DataBaseUtils.loadDatabase(DataBaseUtils.java:118) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.mycontroller.standalone.StartApp.startServices(StartApp.java:243) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.mycontroller.standalone.StartApp.startMycontroller(StartApp.java:106) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.mycontroller.standalone.StartApp.main(StartApp.java:93) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
Caused by: java.lang.NullPointerException: null
        at org.mycontroller.standalone.db.migration.V1_02_08__2016_Jul_01.migrate(V1_02_08__2016_Jul_01.java:75) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        at org.flywaydb.core.internal.resolver.jdbc.JdbcMigrationExecutor.execute(JdbcMigrationExecutor.java:45) ~[mycontroller-dist-standalone-0.0.3.Alpha2-single.jar:0.0.3.Alpha2]
        ... 17 common frames omitted
Exception in thread "MyController.org Shutdown-Hook" java.lang.NullPointerException
        at Acme.Serve.Serve.stopBackground(Serve.java:684)
        at org.jboss.resteasy.plugins.server.tjws.TJWSServletServer.stop(TJWSServletServer.java:184)
        at org.mycontroller.standalone.StartApp.stopHTTPWebServer(StartApp.java:216)
        at org.mycontroller.standalone.StartApp.stopServices(StartApp.java:288)
        at org.mycontroller.standalone.AppShutdownHook$1.run(AppShutdownHook.java:34)
```

**Comment by jkandasa** [comment] 2016-08-03 02:05
@mozzbozz I tried in my raspberry PI and I'm unable to reproduce this issue. 
I do not get any clue on this issue in your environment :( MyController is using `H2DB` database, will be stored at `mycontroller/conf/mycontroller.h2db`. Extract MyController Alpha2 version and run it. If you face this issue again stop and remove `mycontroller/conf/mycontroller.h2db` and start it again. If you still face the issue try to upgrade your Raspberry PI kernal.

I do not have installed desktop and my versions as follows,
```
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.4.11-v7+ #888 SMP Mon May 23 20:10:33 BST 2016 armv7l GNU/Linux
pi@raspberrypi:~ $ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 8.0 (jessie)
Release:	8.0
Codename:	jessie
pi@raspberrypi:~ $ java -version
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) Client VM (build 25.65-b01, mixed mode)
pi@raspberrypi:~ $
```

I do not see any issue, I tested with `zip` file and `tar.gz`.
My `mycontroller/logs/mycontroller.log`
```
pi@raspberrypi:~/mc/mycontroller $ tail -f logs/mycontroller.log 
2016-08-03 07:27:26,025 INFO [main] [org.mycontroller.standalone.AppProperties:407] Created directory location: tmp/
2016-08-03 07:27:26,057 INFO [main] [org.mycontroller.standalone.AppProperties:407] Created directory location: ../conf/resources/scripts/
2016-08-03 07:27:26,059 INFO [main] [org.mycontroller.standalone.AppProperties:407] Created directory location: ../conf/resources/scripts/conditions/
2016-08-03 07:27:26,060 INFO [main] [org.mycontroller.standalone.AppProperties:407] Created directory location: ../conf/resources/scripts/operations/
2016-08-03 07:27:26,062 INFO [main] [org.mycontroller.standalone.AppProperties:407] Created directory location: ../www/configurations
2016-08-03 07:27:32,553 INFO [main] [org.mycontroller.standalone.db.migration.V1_01__Initial_Configuration:398] Migration completed successfully.
2016-08-03 07:27:32,955 INFO [main] [org.mycontroller.standalone.db.migration.V1_01_01__SNAPSHOT:66] Migration completed successfully.
2016-08-03 07:27:33,156 INFO [main] [org.mycontroller.standalone.db.migration.V1_01_02__SNAPSHOT:127] Migration completed successfully.
2016-08-03 07:27:33,329 INFO [main] [org.mycontroller.standalone.db.migration.V1_01_03__SNAPSHOT:48] Migration completed successfully.
2016-08-03 07:27:33,511 INFO [main] [org.mycontroller.standalone.db.migration.V1_01_04__SNAPSHOT:107] Migration completed successfully.
2016-08-03 07:27:33,630 INFO [main] [org.mycontroller.standalone.db.migration.V1_01_05__0_0_3_alpha1:47] Migration completed successfully.
2016-08-03 07:27:34,014 INFO [main] [org.mycontroller.standalone.db.migration.V1_02_04__2016_Apr_25:58] Migration completed successfully.
2016-08-03 07:27:34,027 INFO [main] [org.mycontroller.standalone.db.migration.V1_02_01__2016_Mar_24:308] Migration completed successfully.
2016-08-03 07:27:34,285 INFO [main] [org.mycontroller.standalone.db.migration.V1_02_02__2016_Apr_11:66] Migration completed successfully.
2016-08-03 07:27:39,545 INFO [main] [org.mycontroller.standalone.db.migration.V1_02_03__2016_Apr_14:83] Migration completed successfully.
2016-08-03 07:27:39,994 INFO [main] [org.mycontroller.standalone.db.migration.V1_02_04__2016_Apr_25:58] Migration completed successfully.
2016-08-03 07:27:40,102 INFO [main] [org.mycontroller.standalone.db.migration.V1_02_05__2016_Apr_27:68] Migration completed successfully.
2016-08-03 07:27:40,214 INFO [main] [org.mycontroller.standalone.db.migration.V1_02_06__2016_May_10:49] Migration completed successfully.
2016-08-03 07:27:40,309 INFO [main] [org.mycontroller.standalone.db.migration.V1_02_07__2016_May_19:57] Migration completed successfully.
2016-08-03 07:27:40,530 INFO [main] [org.mycontroller.standalone.db.migration.V1_02_08__2016_Jul_01:104] Migration completed successfully.
2016-08-03 07:27:40,611 INFO [main] [org.mycontroller.standalone.db.migration.V1_02_09__2016_Jul_16:93] Migration completed successfully.
2016-08-03 07:27:40,695 INFO [main] [org.mycontroller.standalone.db.migration.V1_02_10__2016_Jul_29:53] Migration completed successfully.
2016-08-03 07:27:41,718 INFO [main] [org.mycontroller.standalone.db.DataBaseUtils:149] Number of migrations done:16
2016-08-03 07:27:41,720 INFO [main] [org.mycontroller.standalone.db.DataBaseUtils:154] Application information: [Version:0.0.3.Alpha2, Database version:1.02.10 - 2016 Jul 29]
2016-08-03 07:27:44,108 INFO [main] [org.mycontroller.standalone.mqttbroker.MoquetteMqttBroker:51] MQTT Broker started successfully. MqttBrokerSettings(enabled=true, bindAddress=0.0.0.0, httpPort=1883, websocketPort=7080, allowAnonymous=false)
2016-08-03 07:27:48,015 INFO [main] [org.mycontroller.standalone.StartApp:209] TJWS server started successfully, HTTPS Enabled?:false, HTTP(S) Port: [8443]
2016-08-03 07:27:48,018 INFO [main] [org.mycontroller.standalone.StartApp:107] MyController.org server started in [22052] ms
```

**Comment by mozzbozz** [comment] 2016-08-03 14:39
Thank you for your effort! I've manually added the gateway, sensors and stuff again, so I didn't need to apply the backup. Now everything is working (and wow, the interface, just everything is way more polished and functional than I thought it would be in an alpha release, so great work :+1: - just didn't want to always only mention the negative things ;) ).

I'm not closing this issue for now as I want to do some more debugging in the next few days - the information given in your last post will be helpful I think!

> MyController is using H2DB database, will be stored at mycontroller/conf/mycontroller.h2db. Extract MyController Alpha2 version and run it. If you face this issue again, stop and remove mycontroller/conf/mycontroller.h2db and start it again.

Ok, so MyController will recreate the file then? Great, I think that might help me with debugging.

> If you still face the issue try to upgrade your Raspberry PI kernel.

That's something I will certainly try. Also I noticed I hadn't installed a lot of updates since the Raspberry Pi (BTW, it's a modell B rev 2.0) lied around for a while... Maybe that already helps.

But first I will need to find an empty SD-card so I don't break my working system while experimenting...

**Comment by jkandasa** [comment] 2016-08-03 15:08
@mozzbozz Thank you!
> I've manually added the gateway, sensors and stuff again

Every time you have to add your gateway manually. To add available sensors and nodes automatically, you can select your gateway and click on `Actions >> Discover` (supports only for MySensors network)

>Ok, so MyController will recreate the file then?

Yes, MyController will recreate the file(`mycontroller/conf/mycontroller.h2db`) again if it is not available on given location..

**Comment by jkandasa** [comment] 2016-08-10 08:45
Unable to reproduce this issue, closing now. We can reopen later if this issue exists.

**Closed by jkandasa** 2016-08-10 08:45 UTC

**Comment by mozzbozz** [comment] 2016-08-11 13:51
Well, I have no idea what went wrong.

Now after my new SD-card arrived, I installed a fresh Raspbian, configured the locales etc., installed Oracle Java and followed the exact same steps in the installation instructions again. Everything works fine now... Sorry and thank you for your effort! So yes, this issue can be closed.
