### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by WimVerhaert** [mycontroller-org/mycontroller#227] opened 2016-07-19 11:01 UTC
Getting a mysensor crash after an illegalArgumentexception

version is 0.0.3.Alpha2-SNAPSHOT
```
2016-07-19 11:34:55,967 ERROR [Thread-4] [org.mycontroller.standalone.message.MessageMonitorThread:70] RawMessage[RawMessage(gatewayId=1, data=2;65;1;0;244;1075548745, subData=null, isTxMessage=false, networkType=MY_SENSORS)] throws exception while processing!, 
java.lang.IllegalArgumentException: 244
	at org.mycontroller.standalone.provider.mysensors.MySensorsUtils$MYS_MESSAGE_TYPE_SET_REQ.get(MySensorsUtils.java:320) ~[mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at org.mycontroller.standalone.provider.mysensors.MySensorsEngine.updateSetReq(MySensorsEngine.java:56) ~[mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at org.mycontroller.standalone.provider.mysensors.MySensorsEngine.updateMessage(MySensorsEngine.java:37) ~[mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at org.mycontroller.standalone.provider.mysensors.MySensorsRawMessage.<init>(MySensorsRawMessage.java:73) ~[mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at org.mycontroller.standalone.provider.mysensors.MySensorsProviderBridge.executeRawMessage(MySensorsProviderBridge.java:58) ~[mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at org.mycontroller.standalone.message.McMessageUtils.sendToProviderBridge(McMessageUtils.java:519) ~[mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at org.mycontroller.standalone.message.MessageMonitorThread.processRawMessage(MessageMonitorThread.java:64) [mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at org.mycontroller.standalone.message.MessageMonitorThread.run(MessageMonitorThread.java:86) [mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:744) [na:1.8.0]
2016-07-19 11:36:24,475 ERROR [Thread-5] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:93] Exception, 
java.lang.NegativeArraySizeException: null
	at org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm.serialEvent(SerialDataListenerjSerialComm.java:59) ~[mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at com.fazecast.jSerialComm.SerialPort$SerialPortEventListener.waitForSerialEvent(SerialPort.java:913) [mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at com.fazecast.jSerialComm.SerialPort$SerialPortEventListener$1.run(SerialPort.java:861) [mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:744) [na:1.8.0]
[Tue Jul 19 11:38:19 CEST 2016] Accept: java.net.SocketException: Socket closed
2016-07-19 11:38:19,186 ERROR [Quartz_Scheduler_Worker-2] [org.mycontroller.standalone.db.dao.MetricsDoubleTypeDeviceDaoImpl:130] Exception,
org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344) ~[mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at org.h2.message.DbException.get(DbException.java:178) ~[mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at org.h2.message.DbException.get(DbException.java:154) ~[mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at org.h2.message.DbException.get(DbException.java:143) ~[mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1468) ~[mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at org.h2.jdbc.JdbcStatement.checkClosed(JdbcStatement.java:987) ~[mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at org.h2.jdbc.JdbcPreparedStatement.checkClosed(JdbcPreparedStatement.java:1621) ~[mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at org.h2.jdbc.JdbcStatement.checkClosed(JdbcStatement.java:961) ~[mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at org.h2.jdbc.JdbcResultSet.checkClosed(JdbcResultSet.java:3179) ~[mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at org.h2.jdbc.JdbcResultSet.getMetaData(JdbcResultSet.java:143) ~[mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at com.j256.ormlite.jdbc.JdbcDatabaseResults.<init>(JdbcDatabaseResults.java:32) ~[mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at com.j256.ormlite.jdbc.JdbcCompiledStatement.runQuery(JdbcCompiledStatement.java:55) ~[mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at com.j256.ormlite.stmt.SelectIterator.<init>(SelectIterator.java:55) ~[mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at com.j256.ormlite.stmt.StatementExecutor.buildIterator(StatementExecutor.java:247) ~[mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at com.j256.ormlite.stmt.StatementExecutor.query(StatementExecutor.java:196) ~[mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at com.j256.ormlite.dao.BaseDaoImpl.query(BaseDaoImpl.java:265) ~[mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at com.j256.ormlite.stmt.QueryBuilder.query(QueryBuilder.java:361) ~[mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at com.j256.ormlite.stmt.Where.query(Where.java:503) ~[mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at org.mycontroller.standalone.db.dao.MetricsDoubleTypeDeviceDaoImpl.getAggregationRequiredVariableIds(MetricsDoubleTypeDeviceDaoImpl.java:128) ~[mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at org.mycontroller.standalone.metrics.MetricsAggregationBase.aggregateForBucketSensorVariable(MetricsAggregationBase.java:56) [mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at org.mycontroller.standalone.metrics.MetricsAggregationBase.executeBucketByBucket(MetricsAggregationBase.java:220) [mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at org.mycontroller.standalone.metrics.MetricsAggregationBase.runAggregation(MetricsAggregationBase.java:312) [mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at org.mycontroller.standalone.metrics.jobs.MetricsAggregationJob.doRun(MetricsAggregationJob.java:35) [mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at org.knowm.sundial.Job.execute(Job.java:57) [mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:178) [mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
	at org.quartz.core.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:515) [mycontroller-dist-standalone-0.0.3.Alpha2-SNAPSHOT-single.jar:0.0.3.Alpha2-SNAPSHOT]
2016-07-19 11:38:19,191 INFO [MyController.org Shutdown-Hook] [org.mycontroller.standalone.AppShutdownHook:36] Bye, Have a nice day! See you soon
```

**Comment by jkandasa** [comment] 2016-08-03 09:44
@WimVerhaert I am unable to reproduce this issue. Can you guide me to reproduce this one?

looks like `IllegalArgumentException` not a root cause for this issue. Notice log timestamp. It happens few minutes before shutdown.

**Comment by jkandasa** [comment] 2016-08-10 10:01
Unable to reproduce this issue. Closing this.

**Closed by jkandasa** 2016-08-10 10:01 UTC
