### ISSUE TITLE
[Snapshot] Modified sensor configurations overriden by new presentation message

### ISSUE THREAD

**Issue by wengjjpaul** [mycontroller-org/mycontroller#300] opened 2016-11-05 09:59 UTC
Hi. 
In alpha, i could change the sensor name and it saves even when i reset my sensors. But now it clears away when i restart my sensors. I have sensors which publish empty name which i would like to change in the browser. But everytime i change them and i reset the sensors, it reverts back to empty name.

Is it supposed to be like this?

**Comment by jkandasa** [comment] 2016-11-05 14:52
@wengjjpaul Yes, it's by design. I will try to address in someway to keep user value.

**Comment by jkandasa** [comment] 2016-11-07 03:43
@wengjjpaul Kindly check the fix on latest snapshot version and update. Right now ignores only blank values. If node sends any value other than blank will be updated.

This is applicable for node name and sensor name.

**Comment by wengjjpaul** [comment] 2016-11-07 12:06
Thanks. Installed and tested.

**Comment by jkandasa** [comment] 2016-11-07 12:11
@wengjjpaul I did test it locally. Does it work as we expected? If so we can close this ticket.

**Comment by wengjjpaul** [comment] 2016-11-07 12:13
@jkandasa I only used the sensor name for my case. Yes it worked as expected. Thank you.

**Closed** 2016-11-07 12:14 UTC
Labels: enhancement
