### ISSUE TITLE
Variables Graphical View doesn't show up on raspberry pi

### ISSUE THREAD

**Issue by cimba007** [mycontroller-org/mycontroller#236] opened 2016-08-05 19:26 UTC
As I said I don't get the "variable graphical view" to work, neither as widget nor in the sensor-details:

Log stays empty as well, maybe increase the loggerlevel? But I don't know which one:
```
2016-08-05 13:05:49,145 INFO [main] [org.mycontroller.standalone.StartApp:209] TJWS server started successfully, HTTPS Enabled?:true, HTTP(S) Port: [8443]
2016-08-05 13:05:49,146 INFO [main] [org.mycontroller.standalone.StartApp:107] MyController.org server started in [20661] ms
[Fri Aug 05 13:05:55 CEST 2016] IO error: javax.net.ssl.SSLException: Connection has been shutdown: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection? in processing a request from /192.168.178.34:8443 / sun.security.ssl.SSLSocketImpl
2016-08-05 13:07:46,362 INFO [Acme.Utils.ThreadPool(1)-PooledThread: Acme.Serve.Serve$ServeConnection@14b40fc] [org.mycontroller.standalone.gateway.mqtt.MqttGatewayImpl:70] MQTT Gateway[tcp://localhost:1883] connected successfully..
2016-08-05 13:15:17,765 INFO [Acme.Utils.ThreadPool(6)-PooledThread: Acme.Serve.Serve$ServeConnection@293a6b] [org.mycontroller.standalone.mqttbroker.MoquetteMqttBroker:71] MQTT broker restart triggered...
2016-08-05 13:19:24,743 INFO [Acme.Utils.ThreadPool(6)-PooledThread: Acme.Serve.Serve$ServeConnection@62c4af] [org.mycontroller.standalone.gateway.mqtt.MqttGatewayImpl:70] MQTT Gateway[tcp://localhost:1883] connected successfully..
```

PS: This only affects the "Variables graphical view". Other graphical widgets are working fine. This issues affects dashboard and sensor-detail view stuff.

**Comment by cimba007** [comment] 2016-08-05 19:48
Well I found the solution .. blocked by "ublock origin"

**Comment by cimba007** [comment] 2016-08-05 19:53
Maybe remap this path? "metrics/metrics" get blocked on at least "my" adblocker:

![image](https://cloud.githubusercontent.com/assets/3453121/17448909/1c167194-5b57-11e6-8833-4c8a421d0f32.png)

**Comment by jkandasa** [comment] 2016-08-06 06:53
@cimba007 Are you running browser on Raspberry PI? No one reported `metrics/metrics` blocked by ad blocker. This is the first time. Which Ad blocker are you using? I'm using [AdBlock](https://getadblock.com) and I never face issues like this.

**Comment by cimba007** [comment] 2016-08-06 10:57
I am using "uBlock Origin". mycontroller is running on my raspberry and I browse from my main computer running chrome.

The /metrics/metrics gets blocked by an adblock list named:

![image](https://cloud.githubusercontent.com/assets/3453121/17456350/258e6a00-5bd5-11e6-8388-de90f422588a.png)

No big dead as the only thing I had to do was to whitelist my raspberry .. but I remember some1 else having a problem with "widgets loading forever" .. maybe he hat the same addon? (Issue was posted on the forums)

**Comment by cimba007** [comment] 2016-08-06 11:05
Nevertheless .. I noticed the loading time of the graphic is very long on one particular graph.

6 hours .. 1 measurement per seconds = 3600*6 = 21600 to display/calculate average .. where does the caluclation of the graph happen? Does the client calculate the average/min/max over 21600 points or the server? The graph is very slow on my raspberry and on my i5-3570k@4,2ghz so I guess there has to be some hidden bottleneck:

As you can see the graph kind of "stuck" after a few cm and then takes like ~10-15seconds. No "big" deal but maybe something that can be improved .. ofc. I can reduce my note to not send data every seconds for 3 graphcs ;-)

![image](https://cloud.githubusercontent.com/assets/3453121/17456387/406eec68-5bd6-11e6-817d-17dafcc529d2.png)

**Comment by jkandasa** [comment] 2016-08-06 12:01
@cimba007 
>The adblocker I use is "uBlocks origin" (chrome)
>The /metrics/metrics gets blocked by an adblock list named:

It looks like if we have repeated name in url, `uBlocks` blocks it. I will fix this one.

>Nevertheless .. I noticed the loading time of the graphic is very long on one particular graph.

It should not happen. Did you change default settings of `Settings >> Metrics >> Data retention settings`?

>6 hours .. 1 measurement per seconds = 3600*6 = 21600 to display/calculate average .. where does the caluclation of the graph happen? Does the client calculate the average/min/max over 21600 points or the server? The graph is very slow on my raspberry and on my i5-3570k@4,2ghz so I guess there has to be some hidden bottleneck:

All calculation happens on server side. That too with separate thread. When we query takes metric data from database without any calculation. Oracle java is recommended for Raspberry PI.

>As you can see the graph kind of "stuck" after a few cm and then takes like ~10-15seconds. No "big" deal but maybe something that can be improved .. ofc. I can reduce my note to not send data every seconds for 3 graphcs ;-)

This is kind of issue that graph will not get expand loads all the data in few cm. Few cm data loaded immediately?

**Comment by cimba007** [comment] 2016-08-06 12:33
> It should not happen. Did you change default settings of Settings >> Metrics >> Data retention settings?

Nothing changed here. I narrowed down the issue a little bit:

Have a very close look at the first picture. **This is already all data!!! Only the visualization is compressed to 1cm.** After the named time 5-10seconds the graph "expands" .. showing exactly the same data but now only normal. Maybe this is an issue with the width-detection of the window? I am not sure.

![1](https://cloud.githubusercontent.com/assets/3453121/17456735/8fd16dba-5be2-11e6-8b13-42545916513a.png)

![2](https://cloud.githubusercontent.com/assets/3453121/17456739/931c9bac-5be2-11e6-8333-53f8e96b57ec.png)

**Comment by jkandasa** [comment] 2016-08-06 12:38
@cimba007 Yes, there is an issue with graph. In our controller source it is located at https://github.com/mycontroller-org/mycontroller/blob/development/dist/src/main/package/www/controllers/sensors.js#L409

Actual issue: https://github.com/krispo/angular-nvd3/issues/40

I will check a way and fix this one. Thank you!

**Comment by cimba007** [comment] 2016-08-06 12:41
If you have an idea how to fix this feel free to contact me if you need some1 to test the fix. I like your project very much .. looks like a lot of work and dedication went into this project.

**Comment by jkandasa** [comment] 2016-08-10 08:44
@cimba007 I'm unable to reproduce this issue. Can you check by changing value from `1000` to `1500` in your comtroller code on https://github.com/mycontroller-org/mycontroller/blob/development/dist/src/main/package/www/controllers/sensors.js#L415

in installed location >> `mycontroller/www/controllers/sensors.js#L415`

**Comment by cimba007** [comment] 2016-08-11 17:23
I haven't run my sensor node for the last few days. Just started collections values a few hours ago. I will check when I have at least enough values to fill the 6hour window.

**Comment by cimba007** [comment] 2016-08-12 10:04
Currently I cannot reproduce the issue. The graph shows the first cm and now after a split seconds will show the rest (as opposed to 30 sec delay when I opened the issue).

**Comment by jkandasa** [comment] 2016-08-19 06:18
I'm closing this issue. We can reopen if we can reproduce.

**Closed by jkandasa** 2016-08-19 06:18 UTC
Labels: bug
