### ISSUE TITLE
RGB values sent with leading #

### ISSUE THREAD

**Issue by AWiseAd** [mycontroller-org/mycontroller#311] opened 2016-11-20 12:58 UTC
When sending an RGB value with the color picker the value is sent with a leading # (hash) sign. This is not according to MySensors specification. (and incorrectly interpreted by the existing sketches).

**Comment by jkandasa** [comment] 2016-11-21 01:36
@AWiseAd Which version are you using? I am unable to reproduce this issue. I guess you are seeing on MyController resources log? If yes, you are right in side MyController it is using `#`before actual value. However when sending or receiving to MySensors network value will be converted as requires.

##### Sample message for RGBW:
![image](https://cloud.githubusercontent.com/assets/1004403/20468089/ca2cf66c-afb8-11e6-8290-606d069ad5be.png)


##### Sample message for RGB:
![image](https://cloud.githubusercontent.com/assets/1004403/20468111/f3415bba-afb8-11e6-8ce6-7fb1a73edda0.png)

**Comment by AWiseAd** [comment] 2016-11-21 14:16
Looks like I was running an old version (comment in #310)

**Comment by jkandasa** [comment] 2016-11-21 14:40
@AWiseAd ok I am closing this issue, as we do not have it on recent(SNAPSHOT) version

**Closed by jkandasa** 2016-11-21 14:40 UTC
